In [1]:
#Agglomerative_Hierarchical_Clustering- bottom up approach: more popular than Divisive clustering. 

#Agglomerative Clustering: The Agglomerative Clustering class will require two inputs:

# n_clusters: The number of clusters to form as well as the number of centroids to generate.

#linkage: Which linkage criterion to use. The linkage criterion determines which distance to use between sets of observation. The algorithm will merge the pairs of cluster that minimize this criterion

import numpy as np 
import pandas as pd
from sklearn.preprocessing import MinMaxScaler # for normalization within the range min-to-max
from scipy.spatial import distance_matrix 
from sklearn.cluster import AgglomerativeClustering 
from scipy.cluster import hierarchy 
from matplotlib import pyplot as plt

filename = 'cars_clus.csv'
#Read csv
data_frame = pd.read_csv(filename)
print ("Shape of dataset: ", data_frame.shape) # shape will give information about the size of data: row and col
print ("Size of dataset: ", data_frame.size)
#print(data_frame)
#print(data_frame.dtypes)

# DATA CLEANING
# convert pandas dataframe into List:- LIST- 1 dimensional data, Array:- can be anything
aa= data_frame[[ 'sales', 'resale', 'type', 'price', 'engine_s','horsepow', 'wheelbas', 'width', 'length', 'curb_wgt', 'fuel_cap','mpg', 'lnsales']]
print(type(aa))

# convert pandas dataframe into arrays:- LIST- 1 dimensional data, Array:- can be anything
#bb = data_frame[['sales', 'resale', 'type', 'price', 'engine_s','horsepow', 'wheelbas', 'width', 'length', 'curb_wgt', 'fuel_cap','mpg', 'lnsales']] .values  #.astype(float)
#print(type(bb))
aa=aa.apply(pd.to_numeric, errors='coerce')

upd_data = aa.dropna()
upd_data = upd_data.reset_index(drop=True)
upd_data.head(5)
print ("Shape of updated data: ", upd_data.shape)
print ("Size of updated data: ", upd_data.size)

#FEATURE SELECTION
featureset = upd_data[['engine_s',  'horsepow', 'wheelbas', 'width', 'length', 'curb_wgt', 'fuel_cap', 'mpg']] # Select some samples

# NORMALIZATION :- within the range of 0-1

norm_data = featureset.values #returns a numpy array :- .values is used to convert the data into array 
min_max_scaler = MinMaxScaler()
norm_feature_mtx = min_max_scaler.fit_transform(norm_data)
norm_feature_mtx [0:5]

#Clustering
#In agglomerative clustering, at each iteration, the algorithm must update the distance matrix 
#to reflect the distance of the newly formed cluster with the remaining clusters in the forest.

dist_matrix = distance_matrix(norm_feature_mtx,norm_feature_mtx) 
print(dist_matrix)

# MERGING UPWARDS: 
# (1) Maximum or complete linkage minimizes the maximum distance between observations of pairs of clusters.
# (2) Average linkage minimizes the average of the distances between all observations of pairs of clusters.

agglom = AgglomerativeClustering(n_clusters = 6, affinity='euclidean', linkage = 'complete') #AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')
agglom.fit(norm_feature_mtx)
agglom.labels_

# ADD LABELS TO DATA FRAME
upd_data['cluster_'] = agglom.labels_
upd_data.head()

Shape of dataset:  (159, 16)
Size of dataset:  2544
<class 'pandas.core.frame.DataFrame'>
Shape of updated data:  (117, 13)
Size of updated data:  1521
[[0.         0.57777143 0.75455727 ... 0.28530295 0.24917241 0.18879995]
 [0.57777143 0.         0.22798938 ... 0.36087756 0.66346677 0.62201282]
 [0.75455727 0.22798938 0.         ... 0.51727787 0.81786095 0.77930119]
 ...
 [0.28530295 0.36087756 0.51727787 ... 0.         0.41797928 0.35720492]
 [0.24917241 0.66346677 0.81786095 ... 0.41797928 0.         0.15212198]
 [0.18879995 0.62201282 0.77930119 ... 0.35720492 0.15212198 0.        ]]


sales  resale  type  price  engine_s  horsepow  wheelbas  width  length  \
0  16.919  16.360   0.0  21.50       1.8     140.0     101.2   67.3   172.4   
1  39.384  19.875   0.0  28.40       3.2     225.0     108.1   70.3   192.9   
2   8.588  29.725   0.0  42.00       3.5     210.0     114.6   71.4   196.6   
3  20.397  22.255   0.0  23.99       1.8     150.0     102.6   68.2   178.0   
4  18.780  23.555   0.0  33.95       2.8     200.0     108.7   76.1   192.0   

   curb_wgt  fuel_cap   mpg  lnsales  cluster_  
0     2.639      13.2  28.0    2.828         1  
1     3.517      17.2  25.0    3.673         2  
2     3.850      18.0  22.0    2.150         2  
3     2.998      16.4  27.0    3.015         1  
4     3.561      18.5  22.0    2.933         2